#!/usr/bin/python3
import sys
from enum import Enum

ID, FORM, LEMMA, UPOS, XPOS, FEATS, HEAD, DEPREL, DEPS, MISC = range(10)
out = []

for line in sys.stdin:
    if line == "\n" or line[0] == "#":
        continue

    cols = line.split("\t")
    
    # BATS stuffs
    # plurals
    if cols[UPOS] == 'NOUN' and 'Number=Plur' in cols[FEATS] and 'Case=Nom' in cols[FEATS]:
        out.append((cols[LEMMA], cols[FORM]))
    # 3msg
    # out_dict = [(book, {feats: books}), ...]
    if cols[UPOS] == 'VERB' and 'Number=Plur' in cols[FEATS]

for i in out:
    sys.stdout.write("{}\t{}\n".format(i[0], i[1]))
